### PR TITLE
refactor(other): remove editLink and lastUpdated

### PR DESCRIPTION
**Pull request by mahula**
## 🍰 Pullrequest
It is not necessary for website visitors to be presented
- the link to edit pages in the Github repo
- the timestamp of last changes

edit_link_and_date

### Todo
- [x] Remove edit link
- [x] Removelast update information

### CODE REVIEW

**Review by Elweyn — COMMENTED** [review]
Würde @ulfgebhardt drüber schauen lassen, kann ich nicht beurteilen!
Und nur ein Approve geben ohne kenntniss ist uncool!

**Comment by mahula** [comment]
### Before Changes
edit_link_and_date-before

### After Changes
edit_link_and_date-after

**Comment by ulfgebhardt** [comment]
I am not 100% convinced we should do that. At least I'd like to have a discussion on this.

My point: We had a contributor https://github.com/thkoch2001 and I believe he contributed since he saw a spelling mistake on our website and the option to correct it directly below.

**Comment by mahula** [comment]
> I am not 100% convinced we should do that. At least I'd like to have a discussion on this.
> 
> My point: We had a contributor @thkoch2001 and I believe he contributed since he saw a spelling mistake on our website and the option to correct it directly below.

Good point.
The edit link is kept. Removal of latUpdated has been done in #69

**Pull request closed without merging**
